### ISSUE TITLE
Wrong guesses never get reviewed again when using Fibonacci

### ISSUE THREAD

**Issue by benjaminhouy** [jaysonvirissimo/active_recall#22]
I have had reports from users saying flashcards they mark as wrong never get reviewed again. And looking at the code, I feel like there may be an issue. 
```ruby
def wrong
  {
    box: [0, box - 1].max,
    last_reviewed: current_time,
    next_review: nil,
    times_right: times_right,
    times_wrong: times_wrong + 1
  }
end
```
I may be wrong and misunderstand how Fibonacci and Active Recall work, but it looks like that the following happens:

- If a card in box 0 is marked wrong, it's considered failed based on the failed scope and appears at the next review session:

```ruby
scope :failed, -> { where(["box = ? and last_reviewed is not null", 0]) }
```
- If a card who is in a box greater than 0 is marked wrong, it will not appear as failed and therefore will never be reviewed again.

This isn't a problem for people using Leitner because all cards guessed incorrectly go to box 0:

```ruby
def wrong
  {
    box: 0,
    times_right: times_right,
    times_wrong: times_wrong + 1,
    last_reviewed: current_time,
    next_review: nil
  }
end
```

But for people using Fibonacci, this would essentially mean that any wrong guess on a card that's not in box 0 or 1 will never appear again.

**Comment by jaysonvirissimo** [comment]
FYI: Although the associated PR fixes this issue for reoccuring, you may have to manually move the affected items back into the failed state. For example:
```ruby
ActiveRecall::Item
  .where(next_review: nil)
  .where.not(box: 0)
  .update_all(box: 0)
```
